/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-09-10 05:38:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.kck.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import a.b.c.com.kosmo.board.vo.BoardVO;

public final class bookSelectAll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("a.b.c.com.kosmo.board.vo.BoardVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>글 전체 조회</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	/*text-align: center;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td, th {\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tt {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	// 체크박스의 체크 확인하는 함수\r\n");
      out.write("	function checkOnly(chk) {\r\n");
      out.write("		// alert(\"들어온 check!! : \" + chk);\r\n");
      out.write("		var chkObj = document.getElementsByName(\"bnumCheck\");\r\n");
      out.write("		console\r\n");
      out.write("				.log(\"chkObj(bookSelectAll.jsp에서 bnumCheck라는 이름의 데이터요소를 가져온 값입니다. 뭐가 담겨있나) : \"\r\n");
      out.write("						+ chkObj);\r\n");
      out.write("\r\n");
      out.write("		// 추측 : 체크박스를 확인하면서 체크가 안되어있으면 false값 반환하기\r\n");
      out.write("		for (var i = 0; i < chkObj.length; i++) {\r\n");
      out.write("			if (chkObj[i] != chk) {\r\n");
      out.write("				chkObj[i].checked = false;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// jQuery 시작\r\n");
      out.write("	$(document)\r\n");
      out.write("			.ready(\r\n");
      out.write("					function() {\r\n");
      out.write("\r\n");
      out.write("						// 등록하기\r\n");
      out.write("						$(\"#I\").click(function() {\r\n");
      out.write("							location.href = \"testKck/kck/board/board.html\";\r\n");
      out.write("						});\r\n");
      out.write("						// 전체조회\r\n");
      out.write("						$(\"#SALL\")\r\n");
      out.write("								.click(\r\n");
      out.write("										function() {\r\n");
      out.write("											var isudType = document.boardSelectAllForm.ISUD_TYPE.value = \"SALL\";\r\n");
      out.write("											send(isudType);\r\n");
      out.write("										});\r\n");
      out.write("						// 수정하기\r\n");
      out.write("						$(\"#U\").click(function() {\r\n");
      out.write("							// 체크박스에서 체크 확인 결과를 가져옴\r\n");
      out.write("							var nCnt = chkInfo();\r\n");
      out.write("\r\n");
      out.write("							if (nCnt == 0) {\r\n");
      out.write("								// 체크가 하나도 안되어있을 경우\r\n");
      out.write("								console.log(\"체크박스를 체크하세요\");\r\n");
      out.write("								alert(\"체크박스를 체크하세요\");\r\n");
      out.write("							} else {\r\n");
      out.write("								// 체크가 되어있는 경우\r\n");
      out.write("								/*  자바스크립트 버전\r\n");
      out.write("									document.boardSelectAllForm.ISUD_TYPE.value = \"U\";\r\n");
      out.write("									send(document.boardSelectAllForm.ISUD_TYPE.value);\r\n");
      out.write("								 */\r\n");
      out.write("								// jQuery 버전\r\n");
      out.write("								var v1 = $(\"#ISUD_TYPE\").val(\"U\");\r\n");
      out.write("								alert(\"v1 : \" + v1.val());\r\n");
      out.write("								send(v1);\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("						});\r\n");
      out.write("						// 삭제하기\r\n");
      out.write("						$(\"#D\").click(function() {\r\n");
      out.write("							var nCnt = chkInfo();\r\n");
      out.write("\r\n");
      out.write("							if (nCnt == 0) {\r\n");
      out.write("								// 체크가 하나도 안되어있을 경우\r\n");
      out.write("								console.log(\"체크박스를 체크하세요\");\r\n");
      out.write("								alert(\"체크박스를 체크하세요\");\r\n");
      out.write("							} else {\r\n");
      out.write("								// 체크가 되어있는 경우\r\n");
      out.write("								/*  자바스크립트 버전\r\n");
      out.write("									document.boardSelectAllForm.ISUD_TYPE.value = \"U\";\r\n");
      out.write("									send(document.boardSelectAllForm.ISUD_TYPE.value);\r\n");
      out.write("								 */\r\n");
      out.write("								// jQuery 버전\r\n");
      out.write("								var v2 = $(\"#ISUD_TYPE\").val(\"D\");\r\n");
      out.write("								alert(\"v2 : \" + v2.val());\r\n");
      out.write("								send(v2);\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("						});\r\n");
      out.write("						// 체크박스 체크 카운트\r\n");
      out.write("						function chkInfo() {\r\n");
      out.write("							var obj = document.getElementsByName(\"bnumCheck\");\r\n");
      out.write("							var nCnt = 0;\r\n");
      out.write("							// nCnt에 체크된 체크박스의 숫자가 더해진다.\r\n");
      out.write("							// 체크된 체크박스의 총 개수.\r\n");
      out.write("							for (var i = 0; i < obj.length; i++) {\r\n");
      out.write("								if (obj[i].checked == true) {\r\n");
      out.write("									nCnt++;\r\n");
      out.write("								}\r\n");
      out.write("							}\r\n");
      out.write("							console.log(\"nCnt (체크된 체크박스의 수) : \" + nCnt);\r\n");
      out.write("							return nCnt;\r\n");
      out.write("						}\r\n");
      out.write("						// submit\r\n");
      out.write("						function send(isudType) {\r\n");
      out.write("							alert(\"isudType을 보냅니다 : \" + isudType);\r\n");
      out.write("\r\n");
      out.write("							$(\"#boardSelectAllForm\")\r\n");
      out.write("									.attr(\r\n");
      out.write("											{\r\n");
      out.write("												\"action\" : \"/testKck/board?ISUD_TYPE=\"\r\n");
      out.write("														+ isudType,\r\n");
      out.write("												\"method\" : \"GET\",\r\n");
      out.write("												\"enctype\" : \"application/x-www-form-urlencoded\"\r\n");
      out.write("											}).submit();\r\n");
      out.write("\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("					}); // jQeury 종료\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		request.setCharacterEncoding("EUC-KR");
	
      out.write("\r\n");
      out.write("	SELECT ALL\r\n");
      out.write("	");

		Object obj = request.getAttribute("aListAll");
		if (obj == null)
			return;

		ArrayList<BoardVO> aList = (ArrayList<BoardVO>) obj;
		int nCnt = aList.size();
		out.println("전체 조회 건 수 : " + nCnt + " 건");
	
      out.write("\r\n");
      out.write("	<table>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"2\"><font size=\"4\" color=\"green\"> <img\r\n");
      out.write("					src=\"/testKck/img/img_mando/ase.gif\" width=\"25\" height=\"25\"\r\n");
      out.write("					alter=\"image\"> Board TEST\r\n");
      out.write("			</font></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<form name=\"boardSelectAllForm\" id=\"boardSelectAllForm\">\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\"><input type=\"checkbox\" name=\"chkAll\"\r\n");
      out.write("						id=\"chkAll\"></td>\r\n");
      out.write("					<td class=\"tt\">순번</td>\r\n");
      out.write("					<td class=\"tt\">글 번호</td>\r\n");
      out.write("					<td class=\"tt\">글 제목</td>\r\n");
      out.write("					<td class=\"tt\">저자</td>\r\n");
      out.write("					<td class=\"tt\">패스워드</td>\r\n");
      out.write("					<td class=\"tt\">내용</td>\r\n");
      out.write("					<td class=\"tt\">이미지</td>\r\n");
      out.write("					<td class=\"tt\">삭제여부</td>\r\n");
      out.write("					<td class=\"tt\">등록일</td>\r\n");
      out.write("					<td class=\"tt\">수정일</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			");

				// 데이터가 들어있는 갯수 만큼 (=전체 다)
				for (int i = 0; i < nCnt; i++) {
					// bvo에 담는다.
					BoardVO bvo = aList.get(i);
			
      out.write("\r\n");
      out.write("			<tbody>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\"><input type=\"checkbox\" id=\"bnumCheck\"\r\n");
      out.write("						name=\"bnumCheck\" value=\"");
      out.print(bvo.getBnum());
      out.write("\"\r\n");
      out.write("						onclick=\"checkOnly(this)\"></td>\r\n");
      out.write("					<td class=\"tt\">");
      out.print(i + 1);
      out.write("</td>\r\n");
      out.write("					<td class=\"tt\">");
      out.print(bvo.getBnum());
      out.write("</td>\r\n");
      out.write("					<td class=\"tt\">");
      out.print(bvo.getBsubject());
      out.write("</td>\r\n");
      out.write("					<td class=\"tt\">");
      out.print(bvo.getBwriter());
      out.write("</td>\r\n");
      out.write("					<td class=\"tt\">");
      out.print(bvo.getBpw());
      out.write("</td>\r\n");
      out.write("					<td class=\"tt\">");
      out.print(bvo.getBmemo());
      out.write("</td>\r\n");
      out.write("					<td class=\"tt\"><img\r\n");
      out.write("						src=\"testKck/fileupload/board/");
      out.print(bvo.getBphoto());
      out.write("\"></td>\r\n");
      out.write("					<td class=\"tt\">");
      out.print(bvo.getDeleteyn());
      out.write("</td>\r\n");
      out.write("					<td class=\"tt\">");
      out.print(bvo.getInsertdate());
      out.write("</td>\r\n");
      out.write("					<td class=\"tt\">");
      out.print(bvo.getUpdatedate());
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

					} // for문 종료
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td conspan=\"20\" align=\"right\"><input type=\"hidden\"\r\n");
      out.write("						name=\"ISUD_TYPE\" id=\"ISUD_TYPE\" value=\"\"> <input\r\n");
      out.write("						type=\"button\" value=\"등록\" id=\"I\"> <input type=\"button\"\r\n");
      out.write("						value=\"조회\" id=\"SALL\"> <input type=\"button\" value=\"수정\"\r\n");
      out.write("						id=\"U\"> <input type=\"button\" value=\"삭제\" id=\"D\">\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
