/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-09-10 05:38:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.kck.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import a.b.c.com.kosmo.board.service.BoardService;
import a.b.c.com.kosmo.board.service.BoardServiceImpl;
import a.b.c.com.kosmo.board.vo.BoardVO;
import java.util.ArrayList;

public final class boardSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("a.b.c.com.kosmo.board.service.BoardServiceImpl");
    _jspx_imports_classes.add("a.b.c.com.kosmo.board.vo.BoardVO");
    _jspx_imports_classes.add("a.b.c.com.kosmo.board.service.BoardService");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>글 조회</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	/*text-align: center;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div {\r\n");
      out.write("	margin: 50px 0px 0px 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td, th {\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tt {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\";></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function boardUpdate(actionUpdate) {\r\n");
      out.write("		console.log(\"boardSelect.jsp의 boardUpdate함수 진입\");\r\n");
      out.write("\r\n");
      out.write("		if ('U' == actionUpdate) {\r\n");
      out.write("			var v1 = \"UOK\";\r\n");
      out.write("			document.boardUpdateForm.action = \"/testKck/board?ISUD_TYPE=\" + v1;\r\n");
      out.write("		}\r\n");
      out.write("		if ('D' == actionUpdate) {\r\n");
      out.write("			var v2 = \"DOK\";\r\n");
      out.write("			document.boardUpdateForm.action = \"/testKck/board?ISUD_TYPE=\" + v2;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		document.boardUpdateForm.method = \"POST\";\r\n");
      out.write("		document.boardUpdateForm.enctype = \"application/x-www-form-urlencoded\";\r\n");
      out.write("		document.boardUpdateForm.submit();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function checkAction(actionName) {\r\n");
      out.write("		console.log(\"boardSelect.jsp의 checkAction함수 진입\");\r\n");
      out.write("\r\n");
      out.write("		if ('I' == actionName) {\r\n");
      out.write("			location.href = \"/testKck/kck/board/board.html\";\r\n");
      out.write("		}\r\n");
      out.write("		if ('SALL' == actionName) {\r\n");
      out.write("			location.href = \"/testKck/board?ISUD_TYPE=SALL\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		request.setCharacterEncoding("EUC-KR");
	
      out.write("\r\n");
      out.write("	SELECT\r\n");
      out.write("	");

		Object obj = request.getAttribute("aListS");
		if (obj == null)
			return;

		ArrayList<BoardVO> aList = (ArrayList<BoardVO>) obj;
		int nCnt = aList.size();
		out.println("조건 조회 : " + nCnt + " 건");

		String bnum = "";
		String bsubject = "";
		String bwriter = "";
		String bpw = "";
		String bmemo = "";
		String bphoto = "";
		String deleteyn = "";
		String insertdate = "";
		String updatedate = "";

		if (nCnt == 1) {
			BoardVO bvo = aList.get(0);

			bnum = bvo.getBnum();
			bsubject = bvo.getBsubject();
			bwriter = bvo.getBwriter();
			bpw = bvo.getBpw();
			bmemo = bvo.getBmemo();
			bphoto = bvo.getBphoto();
			deleteyn = bvo.getDeleteyn();
			insertdate = bvo.getInsertdate();
			updatedate = bvo.getUpdatedate();

		}
	
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("	<div>\r\n");
      out.write("		<form name=\"boardUpdateForm\" id=\"boardUpdateForm\">\r\n");
      out.write("			<table border=\"1\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\"><font size=\"4\"\r\n");
      out.write("						style=\"color: green;\">게시판 글 수정 && 삭제</font> <img\r\n");
      out.write("						src=\"/testKck/img/img_mando/ase.gif\" width=\"25\" height=\"25\"\r\n");
      out.write("						alt=\"image\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\">글 번호</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"bnum\" id=\"bnum\" size=\"20\"\r\n");
      out.write("						value\"");
      out.print(bnum);
      out.write("\" readonly></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\">제목</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"bsubject\" id=\"bsubject\" size=\"55\"value\"");
      out.print(bsubject);
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\">이름</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"bwriter\" id=\"bwriter\" size=\"20\"\r\n");
      out.write("						value\"");
      out.print(bwriter);
      out.write("\" readonly></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\">비밀번호</td>\r\n");
      out.write("					<td><input type=\"password\" name=\"bpw\" id=\"bpw\" size=\"20\"\r\n");
      out.write("						value\"");
      out.print(bpw);
      out.write("\" readonly></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\">삭제여부</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"deleteyn\" size=\"20\"\r\n");
      out.write("						value\"");
      out.print(deleteyn);
      out.write("\" disable></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\">입력일</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"insertdate\" size=\"20\"\r\n");
      out.write("						value\"");
      out.print(insertdate);
      out.write("\" disable></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\">수정일</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"updatedate\" size=\"20\"\r\n");
      out.write("						value\"");
      out.print(updatedate);
      out.write("\" disable></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\">내용</td>\r\n");
      out.write("					<td><textarea name=\"bmemo\" id=\"bmemo\" rows=\"10\" cols=\"50\">");
      out.print(bmemo);
      out.write("</textarea>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"tt\">사진</td>\r\n");
      out.write("					<td><img src=\"/testKck/fileupload/board/");
      out.print(bphoto);
      out.write("\"\r\n");
      out.write("						border=\"1\" width=\"40\" height=\"50\" alt=\"image\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\"><input type=\"hidden\"\r\n");
      out.write("						name=\"ISUD_TYPE\" id=\"ISUD_TYPE\"> <input type=\"button\"\r\n");
      out.write("						value=\"수정\" onclick=\"boardUpdate('U')\" /> <input type=\"button\"\r\n");
      out.write("						value=\"삭제\" onclick=\"boardDelete('D')\" /> <input type=\"reset\"\r\n");
      out.write("						value=\"취소\" /> &nbsp;&nbsp;&nbsp;&nbsp; <input type=\"button\"\r\n");
      out.write("						value=\"입력\" onclick=\"checkAction('I')\" /> <input type=\"button\"\r\n");
      out.write("						value=\"목록\" onclick=\"checkAction('SALL')\" />\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
